### ISSUE TITLE
omg exec fails for an unknown reason

### ISSUE THREAD

**Issue by judepereira** [microservices/omg-cli#102]
Here's the output of the cli for the AccuWeather service:
```
(venv) h2:accuweather jude$ omg exec forecast -a location="Amsterdam, Netherlands" -e API_KEY=xxx
✔ Built Docker image with name: omg/microservice/accuweather
✔ Stared Docker container with id: 6da4d5d2198d
⠸ Running action: `forecast`TypeError: utils_1.dataTypes[action.output.type] is not a function
    at Object.verifyOutputType (/usr/local/lib/node_modules/omg/dist/verify.js:88:47)
    at HttpExec.<anonymous> (/usr/local/lib/node_modules/omg/dist/commands/exec/HttpExec.js:39:20)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/omg/dist/commands/exec/HttpExec.js:4:58)
utils_1.dataTypes[action.output.type] is not a function(venv) h2:accuweather jude$ 

```

**Comment by TomPed** [comment]
Fixed in a past PR.
